# Generated by Django 2.2.5 on 2019-10-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='hashid',
            field=models.CharField(db_index=True, default='null', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='targetpath',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='targetpvc',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='filename',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
