# Generated by Django 2.2.5 on 2019-10-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20191022_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='hashid',
            field=models.CharField(db_index=True, default='null', max_length=255),
        ),
    ]
