# Generated by Django 2.2.5 on 2019-10-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20191022_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='uploadtime',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='hashid',
            field=models.CharField(db_index=True, default='null', max_length=255, unique=True),
        ),
    ]
