# Generated by Django 2.2.6 on 2019-11-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileModel',
            new_name='ImageModel',
        ),
    ]
