# Generated by Django 2.1.4 on 2019-10-22 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('logs', models.TextField()),
                ('logs_get', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaskSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(max_length=1024)),
                ('container_config', models.TextField()),
                ('time_limit', models.PositiveIntegerField(default=0)),
                ('replica', models.PositiveIntegerField(default=1)),
                ('ttl_interval', models.PositiveIntegerField(default=2)),
                ('max_sharing_users', models.PositiveIntegerField(default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod_name', models.CharField(max_length=255)),
                ('expire_time', models.PositiveIntegerField(db_index=True, default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task_manager.TaskSettings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_model.UserModel')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task_manager.TaskSettings'),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_model.UserModel'),
        ),
    ]
