# Generated by Django 2.1.4 on 2019-11-04 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskVNCPod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod_name', models.CharField(max_length=255)),
                ('url_path', models.CharField(max_length=255)),
                ('vnc_password', models.CharField(max_length=10)),
                ('expire_time', models.PositiveIntegerField(db_index=True, default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task_manager.TaskSettings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
