# Generated by Django 2.1.4 on 2019-11-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_taskvncpod'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='exit_code',
            field=models.IntegerField(default=0),
        ),
    ]
